### ISSUE TITLE
ios problems

### ISSUE THREAD

**Issue by vip32** [javiertoledo/bootstrap-rating-input#15]
on ios (5+7) the rating does not work. stars are not clickable. on an ipad i can change some stars with lots of effort (not smooth). on an iphone no stars can be selected. very strange problem for such a great plugin.

on android/desktop all is working well.

**Comment by cstansbury** [comment]
Note - I've fixed the fastclick incompatibility in [this pull request](https://github.com/javiertoledo/bootstrap-rating-input/pull/31).

**Comment by javiertoledo** [comment]
Fixed in PR #31
