### ISSUE TITLE
Maybe add an explanation of default value to the docs

### ISSUE THREAD

**Issue by johncadigan** [javiertoledo/bootstrap-rating-input#26]
Hello Javier!

Since I recently recieved and e-mail about setting default display values, it might be worth adding an explanation of how you can set default value when it is to be voted upon by seting a value for the input:

<input type="number" data-max="5" data-min="1" name="Difficulty-Rating" id="some_id" class="rating" data-active-icon="fa-star" data-icon-lib="fa fa-2x" data-inactive-icon="fa-star-o" value="${int(difficulty_score)}"/>

I hope you are well,

-John

**Comment by vgoklani** [comment]
Hi - How do I set the default display values? 

Thanks!

**Comment by Ahtenus** [comment]
Hi, just for others reference this is how i managed to set default values:

    <input type="number" name="rating" class="rating" value="3" />

But for some reason it didn't render the stars until one of the stars was hovered, so I added the following line to on DOM ready:

    $(".rating-input i:first-child").trigger('mouseleave');

Cheers,
Viktor

**Comment by tarekadam** [comment]
Thanks Viktor.  That fixed it.

**Comment by javiertoledo** [comment]
I have added a section to the readme explaining how to set a defailt value https://github.com/javiertoledo/bootstrap-rating-input#can-i-set-a-default-value

@Ahtenus the bug you're describing here is fixed on version 0.3.1, thanks for reporting it ;-)
