### ISSUE TITLE
Clear does not reset to minimum assigned value, it resets to 0.

### ISSUE THREAD

**Issue by thomasmaxson** [javiertoledo/bootstrap-rating-input#27]
When "clearing" a selected value, the star system does not reset to the minimum value assigned. The clear button should reset the value to the minimum value designated by the user.

i.e. - If you have a rating system of 1 star - 5 stars. Select 3 stars, then clear the selection. The stars reset to 0, but the minimum value allowed is 1.

**Comment by javiertoledo** [comment]
Thanks for reporting the bug, it's fixed on version 0.3.1
