### ISSUE TITLE
Preset  Default Value

### ISSUE THREAD

**Issue by FraOre** [javiertoledo/bootstrap-rating-input#32]
Hi Javier!

thanks for the good plugin! Very usefull!

Can you add an option to preset the default value. For exampke to 3. So when the plugin is loaded the rate is set on 3 and 3 stars are dark (the other 2 empty...)

**Comment by javiertoledo** [comment]
Maybe this thread helps you https://github.com/javiertoledo/bootstrap-rating-input/issues/26#issuecomment-120304992
