### ISSUE TITLE
how can i change star symbol to the image 

### ISSUE THREAD

**Issue by Raman16** [javiertoledo/bootstrap-rating-input#35]
hi all,i have working recently with star rating plugin...everthing works fine,..but i want star symbol to be changed to the bulb image i required to put for project.how can i do that..please let me know me it..thanks in advance

**Comment by javiertoledo** [comment]
Taking a look to this README section may help: https://github.com/javiertoledo/bootstrap-rating-input#can-i-use-custom-icon-classes
