### ISSUE TITLE
Newbie here: Plus minus rating glyphicon

### ISSUE THREAD

**Issue by Carolannjellyhaus** [javiertoledo/bootstrap-rating-input#36]
Meteor doesn't seem to offer plus minus rating and I am using glyphicons.  Does anyone know where I can get a rating that uses glyphicons or how I would write code so that they would work?

**Comment by javiertoledo** [comment]
You can use custom classes for the icons as you can read here: https://github.com/javiertoledo/bootstrap-rating-input#can-i-use-custom-icon-classes
