### ISSUE TITLE
How to retrieve the number of the star selected by the user?

### ISSUE THREAD

**Issue by help53** [javiertoledo/bootstrap-rating-input#40]
Hello, 

i want to know how do i retrieve the value of the number of the star selected by the user ? 
For example if the user selects 3 star out of 5 , how do i know that he selected three ( the goal is to stock all that in a database). 

What if my users don't want to select any star? all of the 5 star can be unselected how to take out the minimum one star selected ?

thanks for your answer, I really need it .

**Comment by SiteSplat** [comment]
you need back-end functionality for that, like PHP and mySQL...

**Comment by javiertoledo** [comment]
The rating input is designed to behave as a regular HTML input and its value is stored in an `<input type="hidden">..` tag in your DOM, you should be able to send its value to a server if it's embebed in a `<form>` tag or use something like jQuery to read the hidden field value in the client side.
