### ISSUE TITLE
Jquery 3 incompatibility

### ISSUE THREAD

**Issue by fabianpiau** [javiertoledo/bootstrap-rating-input#46]
Bootstrap 3.3.7 is now compatible with jQuery 3.
Unfortunately this plugin is not.

I got the JS exception when I try to rate something:

`TypeError: o.prevAll(...).andSelf is not a function`

**Comment by locpd** [comment]
In bootstrap-rating-input.js, find:
`toggleActive($selected.prevAll('i').andSelf(), true, options);`

replace with:
`toggleActive($selected.prevAll('i').addBack(), true, options);`

and it'll work!

**Comment by fabianpiau** [comment]
Thanks a lot! It works like a charm. Will be great to include this change for the future release!
