### ISSUE TITLE
Add option to always show the "clearable" text and icon, even when nothing is selected

### ISSUE THREAD

**Issue by karllhughes** [javiertoledo/bootstrap-rating-input#48]
Great little plugin. I need to keep the "X" up next to all the star ratings that are clearable, even when the user has not yet chosen a rating.

I'm envisioning creating a new option (`data-clearable-remain`) in the dom and JS that defaults to false. When set to true it will keep the clearable text and link up, even if there are no stars selected.

Working on a PR for this now. Just wanted to record the feature here for reference.

**Comment by javiertoledo** [comment]
Thanks for this, really appreciated
