### ISSUE TITLE
How to setup with AngularJs

### ISSUE THREAD

**Issue by albertotn** [javiertoledo/bootstrap-rating-input#50]
I have some trouble make this library working with angular, because I'm importing the library in main index.hml page and use it in a template page, do you have any idea how to fix it ?

Thanks!

**Comment by javiertoledo** [comment]
Sorry, I've not tried it in Angular projects, but you'll probably need to call manually to `$("input.rating").rating()` manually after you're sure your HTML has been rendered. The library only replaces inputs that are already rendered on load time.
