### ISSUE TITLE
how use id on javascript input ?

### ISSUE THREAD

**Issue by LucasRTI** [javiertoledo/bootstrap-rating-input#51]
I need know what star was rated id="lucas1" or id="lucas2"
Plz its very, very important to me

 ***************_start script**_*******************
  $(function(){
        $('input').on('change',  function(){
       uid2 = $(this).val()
         alert("    <?php  echo "ok";  ?>  " );  }); });
************************_end script**_********************\*  

 input type="number"  id="lucas1" class="rating" data-max="5" data-min="1" data-empty-value="0" 
 input type="number"  id="lucas2" class="rating" data-max="5" data-min="1" data-empty-value="0"

**Comment by javiertoledo** [comment]
Inputs become hidden after the plugin applies, but they keep the ID and the value, maybe you can try something like:

    $("input#lucas1").on('change', function() {
        alert("Lucas 1 has a new value: " + $(this).val());
    });

You can see an example of using jQuery with the inputs in the `demo.html` file https://github.com/javiertoledo/bootstrap-rating-input/blob/master/demo.html#L23
