### ISSUE TITLE
How do i set a dynamic value using javascript

### ISSUE THREAD

**Issue by aneeshsudhakaran** [javiertoledo/bootstrap-rating-input#53]
// This not working 
$('#store-rating').rating({
  value: 2
});

**Comment by LucasRTI** [comment]
hi, i use this
$(function(){
        $('input').on('change', function(){
       uid2 = $(this).val()
   $.post('../../functions/functions.php', { uid1: <?php  echo $uid; ?>, rate:  $(this).val(), function "1" } )
        });
      });

**Comment by aneeshsudhakaran** [comment]
i got another idea from this forum
function assign_val(ratingInputSelector, value) {
        var selectedStar = $(ratingInputSelector).parent().find("[data-value=" + value + "]");
        selectedStar.removeClass('glyphicon-star-empty').addClass('glyphicon-star');
        selectedStar.prevAll('[data-value]').removeClass('glyphicon-star-empty').addClass('glyphicon-star');
        selectedStar.nextAll('[data-value]').removeClass('glyphicon-star').addClass('glyphicon-star-empty');
        selectedStar.siblings('input').val(value).trigger('change');
    }

**Comment by LucasRTI** [comment]
it works?

**Comment by aneeshsudhakaran** [comment]
No.
I used this plugin...
http://plugins.krajee.com/star-rating-demo-advanced-usage#advanced-example-6

Working perfectly.
