### ISSUE TITLE
How many widgets did you search for?

### ISSUE THREAD

**Issue by dandv** [javiertoledo/bootstrap-rating-input#54]
> After searching for existing widgets

I've also searched for widgets and found [quite a few](https://github.com/dandv/comparisons/blob/master/star-rating-widgets.md) that use only CSS, or only SVG, or even just Unicode star characters.

**Comment by javiertoledo** [comment]
Good to know, I guess things have evolved since 2013 when I created this plugin :-)

**Comment by javiertoledo** [comment]
(Updated README accordingly 👍)
