### ISSUE TITLE
Im total noob - pls let me an example for site

### ISSUE THREAD

**Issue by mateusznasada** [javiertoledo/bootstrap-rating-input#57]
Hi man. Im tottaly new about programming.

Pls tem me show and example how to add this rating on the site ? I want to create this ranking with data using a number  of "likes button facebook"

**Comment by javiertoledo** [comment]
Hi, you have many examples in the [demo.html](https://github.com/javiertoledo/bootstrap-rating-input/blob/master/demo.html) file, and some explanations in the [README](https://github.com/javiertoledo/bootstrap-rating-input/blob/master/README.md).
