### ISSUE TITLE
How to add half-star?

### ISSUE THREAD

**Issue by ivadenis** [javiertoledo/bootstrap-rating-input#8]
Great plugin, thanks!

Is there a way to add a half star ratings?

Thanks!

**Comment by sergiorighi** [comment]
+1

**Comment by dandv** [comment]
[Krajee's Bootstrap star rating plugin](http://plugins.krajee.com/star-rating) can add half stars and fractional stars.

**Comment by dandv** [comment]
@LucasRTI: dude, one comment is enough. Also, GitHub supports +1's now. Also, [Krajee's Bootstrap star rating plugin](http://plugins.krajee.com/star-rating) supports half stars and fractional stars.

Please delete your duplicate comments on this issue :)

**Comment by emovere** [comment]
+1
